### ISSUE TITLE
error building for ubuntu focal on launchpad

### ISSUE THREAD

**Issue by hsbasu** [linuxmint/cjs#103]
As Ubuntu does not always provide the latest versions of Cinnamon, I build them for myself on [Launchpad](https://launchpad.net/~mamolinux/+archive/ubuntu/daily-builds).
But the recent revisions of cinnamon prevents the build due to missing dependency debhelper-compat (= 13) ([check log](https://code.launchpad.net/~mamolinux/+archive/ubuntu/daily-builds/+recipebuild/3376028)).
Is it possible to use debhelper-compat (= 12)?

**Comment by Fantu** [comment]
for focal you need to install debhelper from backports (because focal is old and have debhelper < 13), about PPA build in PPA preferences you need set dependencies to backports (by default is disabled)

**Comment by Fantu** [comment]
focal also don't have libmozjs-78-dev and probably will not be supported, clem today changed CI removing mint20 (based on focal) and adding mint21 (based on jammy)

**Comment by hsbasu** [comment]
> for focal you need to install debhelper from backports (because focal is old and have debhelper < 13), about PPA build in PPA preferences you need set dependencies to backports (by default is disabled)

Let me try this.

**Comment by hsbasu** [comment]
@Fantu @clefebvre While building for focal I found the following errors. I used backports as @Fantu suggested.

```
Compiler stderr:
 
Dependency glib-2.0 found: NO found 2.64.6 but need: '>= 2.66.0'
CMake binary for MachineChoice.HOST is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Trying CMake binary cmake for machine MachineChoice.HOST at [None]
Did not find CMake 'cmake'
Found CMake: NO
No CMake binary for machine MachineChoice.HOST not found. Giving up.
Run-time dependency glib-2.0 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency glib-2.0

meson.build:116:0: ERROR: Git program not found.
dh_auto_configure: error: cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 meson .. --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/x86_64-linux-gnu -Dauto_features=enabled -Dprofiler=disabled -Dinstalled_tests=false returned exit code 1
make[1]: *** [debian/rules:16: override_dh_auto_configure] Error 25
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:13: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

**Comment by Fantu** [comment]
cjs 5.4 need also glib-2.0 >= 2.66.0 (have 2.64.6) but is not good backports it, can be present also other missed requirement (not updated in d/control build-deps)
as wrote the better to avoid to try to build on focal and use Jammy instead
the circleci fails for other reason, lmde5 seems for newer meson needed and mint21 fail 1 test, but trying to build on jammy ppa was built successfull as wrote in https://github.com/linuxmint/cjs/pull/104

**Comment by ItzSwirlz** [comment]
The true answer to everything is focal is behind on everything; all dependencies, debhelper, you name it. I guess you could force lower it but that would cause more issues. Unless a Cinnamon 5.2/5.4 backport is requested for focal I do not have any intent to do that, though I should ask people.

**Comment by hsbasu** [comment]
> if you exclude cjs 5.4, that is a rebase that don't change mozjs version so don't need js functions changes in cinnamon FWIK you should able to build all other components in focal, I also built them in muffin rebase tests until few days ago and I started works with cjs 5.4 only in latest days

I also observed the same. Its only `cjs` which failed to build for focal.

**Comment by hsbasu** [comment]
I observed that it's not only `glib-2.0`, there are many packages that have to be back-ported. So i am closing this.
