### ISSUE TITLE
cjs-5.6.1 fails to build with clang >=15 on gentoo linux (and elsewhere)

### ISSUE THREAD

**Issue by drwulsen** [linuxmint/cjs#115]
compiling cjs-5.6.1 with clang >=15 breaks the build and exits with an error like:
`"/usr/include/c++/v1/__random/uniform_int_distribution.h:162:5: error: static assertion failed due to requirement '__libcpp_random_is_valid_inttype<char32_t>::value': IntType must be a supported integer type
    static_assert(__libcpp_random_is_valid_inttype<_IntType>::value, "IntType must be a supported integer type");"`
the patch found [here](https://gitlab.gnome.org/GNOME/gjs/-/commit/9b11ed0ba70718a8b1983126563cea58658a808f.diff) fixes the issue and the build goes through.
The issue is mentioned on the [gjs gitlab page](https://gitlab.gnome.org/GNOME/gjs/-/issues/514)

**Comment by SparkyBluefang** [comment]
Pretty sure this was fixed in #111 / 5.8.0
