### ISSUE TITLE
installed-tests/js/meson.build:206:3: ERROR: Unknown variable "have_gtk4".

### ISSUE THREAD

**Issue by SparkyBluefang** [linuxmint/cjs#117]
I ran into this build error when packaging for Gentoo. It looks like this has already been reported and fixed upstream.

https://gitlab.gnome.org/GNOME/gjs/-/issues/532
https://gitlab.gnome.org/GNOME/gjs/-/merge_requests/830

**Comment by mtwebster** [comment]
Thanks, fixed:
https://github.com/linuxmint/cjs/commit/fb480aae4eff422c3acd275c0108e970eafcdcb9
