### ISSUE TITLE
Port cjs to mozjs 115

### ISSUE THREAD

**Issue by bgermann** [linuxmint/cjs#120]
Please consider porting to mozjs 115 which is used by the current Firefox ESR release.

**Comment by Fantu** [comment]
mozjs102 fails to build with python 3.12, so seems this becomes important for Debian 13 and even earlier for Ubuntu 24.04
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1066872
@clefebvre @mtwebster

**Comment by leigh123linux** [comment]
@Fantu  Patch it!

https://src.fedoraproject.org/rpms/mozjs102/c/72d6ad552c3087fafb475370b1a8a7ec9ee39700?branch=rawhide

**Comment by Fantu** [comment]
@leigh123linux thanks for the patch, as Ubuntu 24.04 is already in freeze this seems better (instead gjs rebase now)

**Comment by bgermann** [comment]
Fixed by f99dbea9cd7be98b70446d65315774e2ff0bd483
