### ISSUE TITLE
What is doing the Garbage Collector? cinnamon --replace

### ISSUE THREAD

**Issue by ghost** [linuxmint/cjs#15]
I move this from here: https://github.com/linuxmint/Cinnamon/issues/3635

cinnamon --replace is eating the memory, and the garbage collector do not recover the memory, or just can recovered only a fraction...

I make this test with the default cinnamon configuration.

Windows list, cinnamon menu, and some applet need more memory, that others and with this applets you can see more clear any problem in memory. They need to use a lot of memory to show several things, but this memory need to be recover when garbage collector do a clean... This is not what happen...

This probably not occurs only in cinnamon 2.4 also possible in cinnamon 2.2.16, like this comment:
jake-phy/WindowIconList#62 or also possible with cinnamon 2.2.8 like this comment: lestcape/Configurable-Menu#58

Procedure to detect problems:
Open the procces monitor, then wait a while without do any thing. When the memory will be stable, open the menu, then wait a while and you will see that the memory usage will increase. This is normal...

Close the menu and repeat the process and you will see how always cinnamon --replace will use more and more memory...

If you do this procedure, waiting always some time between all actions, you can note when the garbage collector do a clean, and you can see that the garbage collector only removed a little fraction of all memory that will lost.

This is not the behavior that I expect to happen, the garbage collector need to return the memory that we lost, to can be used to other applications.

Could anyone verify that ?

This appear to be seriously:
https://bugzilla.gnome.org/buglist.cgi?quicksearch=product%3A%22gnome-shell%22++memory+leak
https://bugzilla.gnome.org/show_bug.cgi?id=685513
https://bugzilla.redhat.com/show_bug.cgi?id=977387
https://mail.gnome.org/archives/gtk-devel-list/2014-February/msg00027.html

More people reporting the same in differents cinnamon versions: http://forum.linuxmint.com/viewtopic.php?f=208&t=153281

If there are a fix, this will be here: https://bugzilla.gnome.org/show_bug.cgi?id=725099

**Comment by lestcape** [comment]
@mtwebster thanks for merged the pull, I can not be complete sure yet (i need to return to the default cinnamon configuration), but apparently my memory problem is gone... I have some memory problems on my current configuration that increase my memory, but only i get MB on a day , not GB on hours. And yes, apparently is causing by Configurable Menu and exactly when i change the menu layout.
Thanks.
