### ISSUE TITLE
cjs check error

### ISSUE THREAD

**Issue by alihanozturk** [linuxmint/cjs#27]
http://www.sudrap.org/paste/text/662956/

glib2 installed

**Comment by mtwebster** [comment]
does gtester run in a terminal?

it's part of libglib2.0-dev on Ubuntu/Mint

**Comment by alihanozturk** [comment]
0f23c01ad10e ~ # gtester
Usage:
gtester [OPTIONS] testprogram...

Help Options:
  -h, --help                    Show this help message

Utility Options:
  -v, --version                 Print version informations
  --g-fatal-warnings            Make warnings fatal (abort)
  -k, --keep-going              Continue running after tests failed
  -l                            List paths of available test cases
  -m {perf|slow|thorough|quick} Run test cases according to mode
  -m {undefined|no-undefined}   Run test cases according to mode
  -p=TESTPATH                   Only start test cases matching TESTPATH
  -s=TESTPATH                   Skip test cases matching TESTPATH
  --seed=SEEDSTRING             Start tests with random seed SEEDSTRING
  -o=LOGFILE                    Write the test log to LOGFILE
  -q, --quiet                   Suppress per test binary output
  --verbose                     Report success per testcase

**Comment by alihanozturk** [comment]
./test/run-with-dbus: line 163  $WRAPPED_SCRIPT "$@" 2>>"$STDERR_LOGFILE" || "****************  script \"$WRAPPED_SCRIPT\" failed"

******************* ???
