### ISSUE TITLE
JS WARNING reported by the use of CJS 3.4.x on Cinnamon 3.4.x

### ISSUE THREAD

**Issue by Odyseus** [linuxmint/cjs#46]
Hello, everybody.

The following is a warning logged into the **.xsession-errors** file when using CJS 3.4.1 on Cinnamon 3.4.1.

> Cjs-Message: JS WARNING: [resource:///org/cinnamon/cjs/modules/tweener/tweener.js 547]: reference to undefined property properties[istr].isSpecialProperty

> System:    Kernel: 4.4.0-21-generic x86_64 (64 bit gcc: 5.3.1)
>            Desktop: Cinnamon 3.4.1 (packages from ppa:gwendal-lebihan-dev/cinnamon-nightly built on 2017-06-11)
>            Distro: Linux Mint 18.1 Serena
>            Cjs: 3.4.1 (built from source on 2017-06-06)

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cjs/commit/c7cb693a4e91b05f8ccd8237307f16e1923f7be6

**Comment by Odyseus** [comment]
@leigh123linux 

Look again. It's the property bellow the one that you fixed (`properties[istr].isSpecialProperty`) and it is a boolean.

**Comment by JosephMcc** [comment]
Yeah, I thought the same as @leigh123linux when I first saw it.
