### ISSUE TITLE
Port cjs to mozjs52

### ISSUE THREAD

**Issue by jbicha** [linuxmint/cjs#52]
GNOME 3.26 will be released next month with gjs 1.50 and mozjs52.

It would be great if Cinnamon could work with mozjs52.

Ubuntu 17.10 Alpha has a mozjs52 package you could use. The Debian GNOME team is working to get mozjs52 into Debian. (mozjs38 might never be packaged in Debian.)

The gjs maintainer has interesting info on his blog. Here's a recent post:
https://ptomato.wordpress.com/2017/07/30/modern-javascript-in-gnome-guadec-2017-talk/

**Comment by leigh123linux** [comment]
This isn't going to happen for at least 12 - 18 months so Debian will need to package mozjs38.

**Comment by clefebvre** [comment]
Well there's no plan for 3.6 on this, but long term we'll need to consider it. I'm reopening the issue in the meantime.

**Comment by Fantu** [comment]
About this there also this bug open in ubuntu:
https://bugs.launchpad.net/ubuntu/+source/cjs/+bug/1728184
mozjs38 is no longer supported by Mozilla 
setted with importance high
