### ISSUE TITLE
cjs-3.6.1 Compile Error

### ISSUE THREAD

**Issue by lhw828** [linuxmint/cjs#60]
> checking whether ln -s works... yes
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for gawk... (cached) gawk
./configure: line 16391: AX_COMPILER_FLAGS: command not found
checking whether to build with code coverage support... no
./configure: line 16629: syntax error near unexpected token -lgcov,,' ./configure: line 16629:AX_CHECK_LINK_FLAG(-lgcov,,'

[cjs-3.6.1.log](https://github.com/linuxmint/cjs/files/1504703/cjs-3.6.1.log)

**Comment by leigh123linux** [comment]
Insufficient info provided

**Comment by lhw828** [comment]
@leigh123linux Why is this?

**Comment by lhw828** [comment]
@leigh123linux my autoconf version is 2.69

**Comment by lhw828** [comment]
@leigh123linux and my automake version is 1.15.1

**Comment by leigh123linux** [comment]
autoconf and automake isn't autoconf-archive

```
$ rpm -q --info autoconf-archive
Name        : autoconf-archive
Version     : 2017.09.28
Release     : 1.fc28
Architecture: noarch
Install Date: Mon 23 Oct 2017 14:31:15 BST
Group       : Unspecified
Size        : 2394051
License     : GPLv3+ with exceptions
Signature   : RSA/SHA256, Sat 30 Sep 2017 23:24:53 BST, Key ID e08e7e629db62fb1
Source RPM  : autoconf-archive-2017.09.28-1.fc28.src.rpm
Build Date  : Sat 30 Sep 2017 15:21:01 BST
Build Host  : unused
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.gnu.org/software/autoconf-archive/
Summary     : The Autoconf Macro Archive
Description :
The GNU Autoconf Archive is a collection of more than 450 macros for
GNU Autoconf that have been contributed as free software by friendly
supporters of the cause from all over the Internet.
```

**Comment by lhw828** [comment]
@leigh123linux Than you!
