### ISSUE TITLE
autogen fail in ver4.0

### ISSUE THREAD

**Issue by bhzhu203** [linuxmint/cjs#71]
Makefile-test.am:263: error: CODE_COVERAGE_ENABLED does not appear in AM_CONDITIONAL
Makefile.am:158:   'Makefile-test.am' included from here
Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1

then I remove the CODE_COVERAGE_ENABLED from Makefile-test.am:263
./configure: line 16993: AX_COMPILER_FLAGS: command not found
./configure: line 16995: AX_CODE_COVERAGE: command not found
./configure: line 16996: syntax error near unexpected token `-lgcov,,'
./configure: line 16996: `AX_CHECK_LINK_FLAG(-lgcov,,'

autogen fail in ver4.0  of ubuntu/archlinux latest

**Comment by leigh123linux** [comment]
You haven't got autoconf-archive package installed.
