### ISSUE TITLE
Can't build CJS 4.0.0 on openSUSE Leap 15.1

### ISSUE THREAD

**Issue by terrestrian** [linuxmint/cjs#77]
I am trying to build CJS 4.0.0 but make fails. 
Here is what I get when I run "make check"
[output-make-check.txt](https://github.com/linuxmint/cjs/files/3232141/output-make-check.txt)

**Comment by leigh123linux** [comment]
Use the configure option --disable-Werror to fix

**Comment by terrestrian** [comment]
So is it completely safe to ignore these errors?

**Comment by leigh123linux** [comment]
They are warnings, it's seems Suse sets gcc the  -Werror flag  which makes all warnings into errors.
It isn't normal to use it for normal code compilation.
