### ISSUE TITLE
Cannot compile 4.0.0r1 on Gentoo unstable

### ISSUE THREAD

**Issue by EGStein** [linuxmint/cjs#78]
Hello, I currently cannot upload the build log but it is very simular to the one posted on the gentoo bugzilla.

https://bugs.gentoo.org/686374

It is suspected that it is a upstream bug. 

**Author's edit:** the build log for my system is here: [build.txt](https://github.com/linuxmint/cjs/files/3319127/build.txt)

**Comment by leigh123linux** [comment]
Feel free to reopen if you can provide the actual build error!

**Comment by EGStein** [comment]
It took me quite a while to get this up here, apologies for the delays and confusion.
[build.txt](https://github.com/linuxmint/cjs/files/3319127/build.txt)

**Comment by leigh123linux** [comment]
I believe I fixed this https://github.com/linuxmint/cjs/commit/ea081f3272d5dfb78eceef47826acf90db5d4bdd

Try cjs-4.2 release https://github.com/linuxmint/cjs/releases/tag/4.2.0
