### ISSUE TITLE
Very high entry threshold 

### ISSUE THREAD

**Issue by fedor-elizarov** [linuxmint/cjs#79]
I recently switched from Gnome to Cinnamon and decided to stay on it. For myself, first of all, I wanted to make several extensions, but.

1 - The documentation is incorrect even for the simplest example http://developer.linuxmint.com/reference/git/cinnamon-tutorials/write-applet.html

```diff
- Util.spawn ('xkill');
+ Util.spawn (['xkill']);
```

2 - In that documentation there are either references to gnome projects,
or the indication "look at the source" which is fragmented and generally not clear.

For example, I want to capture a window and display it in a widget as I come across http://developer.linuxmint.com/reference/git/cinnamon-tutorials/importer.html I understand that I need Clutter + St and that's it, I I don’t know what I can use from Clutter and I don’t know how, in principle, I can use St, how can I find out the cjs API Reference? And my only way is to either look for a ready-made extension that already does almost what I need and modify it, but if there isn’t one, I’ll have to manually look in the source for what calls are available to me.

Perhaps I misunderstand the very essence of creating extensions and bindings to libraries. But no, I don’t swear, I just want to make extensions for myself and the community (if they are useful), but for me now it looks like "go there I don’t know where, find that I don’t know what"

Just even basic things like https://github.com/linuxmint/cjs/tree/master/examples

Does not work :(

If I get information to / usr / share / cinnamon / js for more information, this is even more confusing.

Maybe somewhere to describe how to actually make serious extensions? Where to get information about available APIs.
Surely for some people, everything is simple and easy, but I'm a person who can easily navigate in complex C code, I’m just confused, I don’t understand how to do something without crutches and constant peeping into third-party extensions / applets /.

Personally, I wonder how people write extensions, Gnome-shell has the same problem. Torn documentation and word-of-mouth knowledge transfer in forums.

Thanks for reading. Good and peace ^. ^

**I apologize for my English. I used a translator**

**I do not demand anything and do not swear, I just bring you information** 

I write here because it is here that everything connected with the Cinnamon shell begins

**Comment by Odyseus** [comment]
Hello, @fedor-elizarov.

For an updated documentation, install the packages `devhelp` and `cinnamon-doc`. Then open Devhelp from your applications menu. It not only contains a more up-to-date documentation that the one on-line, but also has documentations about the **St** library and Cinnamon's JavaScrit modules.

For documentation about GObject libraries (Clutter, GLib, Gio, etc.), exists [this on-line documentation](https://lazka.github.io/pgi-docs/) that can also be [downloaded for off-line use](https://github.com/lazka/pgi-docs) as a static HTML site, and also can be downloaded as [Devhelp books](https://github.com/pygobject/pgi-docs-devhelp).

**Comment by fedor-elizarov** [comment]
>cinnamon-doc devhelp

Oh thanks bro!  Indeed, everything is written quite openly there, thanks a lot again. I'm going to read! Rays of goodness to you :heart:
