### ISSUE TITLE
Info spam in xsession-errors

### ISSUE THREAD

**Issue by Soapux** [linuxmint/cjs#81]
This is in .xsession-errors every time Cinnamon is started,  I assumed it's from cjs based on the messages.   It would be nice if this could be turned off.  

Cjs-Message: 23:04:16.198: JS LOG: About to start Cinnamon
Cjs-Message: 23:04:16.262: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 62 ms
Cjs-Message: 23:04:16.268: JS LOG: [LookingGlass/info] loading default theme
Cjs-Message: 23:04:16.344: JS LOG: [LookingGlass/info] PlacesManager: Updating devices
Cjs-Message: 23:04:16.348: JS LOG: [LookingGlass/info] loaded at Mon Feb 10 2020 23:04:16 GMT-0600 (CST)
Cjs-Message: 23:04:16.348: JS LOG: Cinnamon started at Mon Feb 10 2020 23:04:16 GMT-0600 (CST)
Cjs-Message: 23:04:16.358: JS LOG: [LookingGlass/info] ExtensionSystem started in 2 ms
Cjs-Message: 23:04:16.358: JS LOG: [LookingGlass/info] DeskletManager started in 0 ms
Cjs-Message: 23:04:16.358: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms
openGL version 3.1 detected (GL3 Cogl Driver)
Cjs-Message: 23:04:16.397: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 16 ms
St-Message: 23:04:16.397: cogl npot texture sizes SUPPORTED
Cjs-Message: 23:04:16.426: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 30 ms
Cjs-Message: 23:04:16.442: JS LOG: [LookingGlass/info] Loaded applet user@cinnamon.org in 16 ms
Cjs-Message: 23:04:16.450: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 23:04:16.451: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 8 ms
Cjs-Message: 23:04:16.463: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 12 ms
Cjs-Message: 23:04:16.511: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 23:04:16.518: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 56 ms
Cjs-Message: 23:04:16.523: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 23:04:16.527: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 8 ms
Cjs-Message: 23:04:16.542: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 14 ms
Cjs-Message: 23:04:16.547: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 4 ms
Cjs-Message: 23:04:16.581: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 34 ms
Cjs-Message: 23:04:16.614: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 34 ms
Cjs-Message: 23:04:16.699: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 84 ms
Cjs-Message: 23:04:16.700: JS LOG: [LookingGlass/info] AppletManager started in 352 ms
Cjs-Message: 23:04:16.701: JS LOG: [LookingGlass/info] Cinnamon took 502 ms to start
Cjs-Message: 23:04:16.721: JS LOG: Unknown network device type, is 14
Cjs-Message: 23:04:16.726: JS LOG: Unknown network device type, is 17
Cjs-Message: 23:04:16.964: JS LOG: [LookingGlass/info] Hiding systray: network

**Comment by leigh123linux** [comment]
We need this to aid diagnostics.
