### ISSUE TITLE
gjs_coverage_enable with cjs

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/cjs#86]
When trying to use cjs, you'll get this:
cjs: symbol lookup error: cjs: undefined symbol: gjs_coverage_enable

I even built this myself and installed the Debian experimental version; no luck.

I also tried fixing it myself; but it screwed up the tests and was a chain reaction essentially.

I'll try investigating but for now this is the problem.

**Comment by leigh123linux** [comment]
Works here.

```
[leigh@mpd Desktop]$ cjs --coverage-prefix=test.js --coverage-output=$(pwd) test.js
Cjs-Message: 01:25:34.454: Wrote coverage statistics to /home/leigh/Desktop/coverage.lcov
[leigh@mpd Desktop]$ cjs --version
cjs 4.7.0
```

test.js

```
function main() {
}
```

**Comment by ItzSwirlz** [comment]
So should cjs automatically write coverage statistics?

**Comment by ItzSwirlz** [comment]
I think that's probably the answer here; but I'll need to see if gjs has this problem too. I'll be honest, I doubt it does.

**Comment by ItzSwirlz** [comment]
I rebuilt/reinstalled cjs 4.7.0 with the new commits you and mtwebster have posted, and I can't replicate this while running CJS with GNOME Maps
